# Might be: localhost, 127.0.0.1, 0.0.0.0, or <your-ip>
host: '0.0.0.0'

# An open port to bind to.
port: 8912

# Use texture hashes instead of UUIDs?
# This won't work when running a standalone AvatarServer.
# You'll need to always use hashes.
use-texture-hashes: true
